### ISSUE TITLE
Update for new app

### ISSUE THREAD

**Issue by C-h-a-r** [thenameisajay/Stagecoach-Clone#4]
Could you update this to fit the style of the new app?

**Comment by thenameisajay** [comment]
@C-h-a-r ,I hope this message finds you well. I would like to express my interest in updating the style for the new app, though I must admit that I am not yet familiar with its features. As of now, I am not residing in Scotland.

Regrettably, I no longer have access to the current ticket or the ability to use the app. Your assistance in providing any necessary information or guidance would be greatly appreciated.
